// _data/importMap.js
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export default async function () {
  const srcDir = path.resolve(__dirname, '../src');
  const imports = {};
  const utilityFiles = [];

  // 1. Scan your files recursively
  function scanDir(currentDir) {
    if (!fs.existsSync(currentDir)) return;

    const items = fs.readdirSync(currentDir);
    for (const item of items) {
      const fullPath = path.join(currentDir, item);
      const stat = fs.statSync(fullPath);

      if (stat.isDirectory()) {
        scanDir(fullPath);
      } else if (item.endsWith('.js')) {
        if (fullPath.split(path.sep).includes('components')) {
          const name = path.basename(item, '.js');
          imports[name] = `/js/${item}`;
          utilityFiles.push(item); // Keep track of files found
        }
      }
    }
  }

  scanDir(srcDir);

  // 2. Generate the Cloudflare _headers file content dynamically
  let headersContent = `# Auto-generated by _data/importMap.js at build time\n\n`;

  // Append rules for every specific utility file discovered
  for (const file of utilityFiles) {
    headersContent += `/js/${file}\n`;
    headersContent += `  Cache-Control: public, max-age=86400, stale-while-revalidate=3600\n\n`;
  }

  // Catch-all rule at the bottom for your Eleventy page bundles
  headersContent += `/js/*\n`;
  headersContent += `  Cache-Control: public, max-age=31536000, immutable\n`;

  // Write the file directly to your source folder
  const headersOutputPath = path.join(srcDir, '_headers');
  fs.writeFileSync(headersOutputPath, headersContent, 'utf-8');

  // Return the imports data back to your WebC templates
  return {
    imports,
  };
}
